# Generated by Django 6.0.3 on 2026-05-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='topic_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
